### ISSUE TITLE
请问如何私有化部署在自己的docker上

### ISSUE THREAD

**Issue by sigusr1** [hai-zou/hexo-theme-sea#41]
前端小白请教，如何私有化部署。

**Comment by hai-zou** [comment]
你可以把我项目中的example拷贝出来试一试，然后网上搜索 "docker 上如何部署 hexo 项目"，应该是有挺多教程的。

**Comment by hai-zou** [comment]
> 前端小白请教，如何私有化部署。

你可以把我项目中的example拷贝出来试一试，然后网上搜索 "docker 上如何部署 hexo 项目"，应该是有挺多教程的。
